# numpy

In [1]:
import numpy as np

a = np.array([1, 2, 3], dtype= 'int16') #initialization
b = np.array([[4, 5, 6],[5, 6, 7]])

In [2]:
a*b #so, 1D array can be multiplied to 2D array

array([[ 4, 10, 18],
       [ 5, 12, 21]])

In [3]:
b.ndim, b.shape

(2, (2, 3))

In [4]:
a.ndim, a.shape

(1, (3,))

In [5]:
a.dtype, b.dtype

(dtype('int16'), dtype('int64'))

In [6]:
#size of each elemet/item
a.itemsize, b.itemsize #gives in bytes

(2, 8)

In [7]:
#num of elements
a.size, b.size

(3, 6)

# accessing/changing specific rows and columns|

In [8]:
print(b)
b[-1, 2], b[:,0]

[[4 5 6]
 [5 6 7]]


(7, array([4, 5]))

In [9]:
c = np.array([[[2, 8, 6, 8],[5, 9, 3, 2]] ,[[9,5,7,0],[6,1,0,4]], [[2, 8, 6, 8],[5, 9, 3, 2]]])
c

array([[[2, 8, 6, 8],
        [5, 9, 3, 2]],

       [[9, 5, 7, 0],
        [6, 1, 0, 4]],

       [[2, 8, 6, 8],
        [5, 9, 3, 2]]])

In [10]:
c.ndim, c.shape

(3, (3, 2, 4))

In [11]:
print(c[1, 0, 2])
c[1, 0, 2] = -5
c

7


array([[[ 2,  8,  6,  8],
        [ 5,  9,  3,  2]],

       [[ 9,  5, -5,  0],
        [ 6,  1,  0,  4]],

       [[ 2,  8,  6,  8],
        [ 5,  9,  3,  2]]])

In [12]:
print(c[-1, :, 0])
c[-1, :, 0] = -1
c

[2 5]


array([[[ 2,  8,  6,  8],
        [ 5,  9,  3,  2]],

       [[ 9,  5, -5,  0],
        [ 6,  1,  0,  4]],

       [[-1,  8,  6,  8],
        [-1,  9,  3,  2]]])

In [13]:
c[-1, :, 0:4:2 ]

array([[-1,  6],
       [-1,  3]])

# initializing

In [14]:
z = np.zeros((2,3,5))
o = np.ones((6, 1), dtype = 'int16')

In [15]:
z

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [16]:
o

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=int16)

In [17]:
an = np.full((2,3), 5, dtype = 'float') #shape, value
#similar to this is full_like
bu = np.full_like(b, 6)

In [18]:
an.shape,  an.dtype

((2, 3), dtype('float64'))

In [19]:
an, bu

(array([[5., 5., 5.],
        [5., 5., 5.]]),
 array([[6, 6, 6],
        [6, 6, 6]]))

In [20]:
#random int initializations
r = np.random.rand(3,2)
r

array([[0.13417472, 0.4015848 ],
       [0.50286952, 0.62852514],
       [0.0610439 , 0.22357865]])

In [21]:
#similar to full like, if you want to pass a tuple
ru = np.random.random_sample(b.shape)
ru, b.shape

(array([[0.07467687, 0.63004302, 0.59496982],
        [0.01337965, 0.51906253, 0.54224624]]),
 (2, 3))

In [22]:
np.random.randint([1, 5, 9], 13)

array([ 7, 11, 10])

# *example array*

In [23]:
e = np.ones((5,5), dtype = 'int16')
e[1:4, 1:-1] = 0
e[2, 2] = 9
print(e)

p = e #it's like pointer switching
p[0] = -100
print(e)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[-100 -100 -100 -100 -100]
 [   1    0    0    0    1]
 [   1    0    9    0    1]
 [   1    0    0    0    1]
 [   1    1    1    1    1]]


In [24]:
np.sin(a)

array([0.841471 , 0.9092974, 0.14112  ], dtype=float32)

### **Linear Algebra**

In [25]:
a = np.ones((2, 3))
b = np.full((3, 2), 6)

np.matmul(b, a)

array([[12., 12., 12.],
       [12., 12., 12.],
       [12., 12., 12.]])

# main things that will be needed in ML

In [26]:
stats = np.array([[2, 8, 6, 8],[5, 9, 3, 2,],[9, 5, 7, 0],[6, 1, 0, 4]])

print(stats)
np.min(stats, axis=0) #horizontal axis=1, vertically 0

[[2 8 6 8]
 [5 9 3 2]
 [9 5 7 0]
 [6 1 0 4]]


array([2, 1, 0, 0])

In [27]:
stats.shape

(4, 4)

In [28]:
print(c)
np.min(c, axis=1) #so, using axis for arrays above 2D will flatten them

[[[ 2  8  6  8]
  [ 5  9  3  2]]

 [[ 9  5 -5  0]
  [ 6  1  0  4]]

 [[-1  8  6  8]
  [-1  9  3  2]]]


array([[ 2,  8,  3,  2],
       [ 6,  1, -5,  0],
       [-1,  8,  3,  2]])

In [29]:
np.min(c, axis=0)

array([[-1,  5, -5,  0],
       [-1,  1,  0,  2]])

In [30]:
np.sum(stats, axis=1) , np.sum(c, axis=1), np.sum(c, axis=0)

(array([24, 19, 21, 11]),
 array([[ 7, 17,  9, 10],
        [15,  6, -5,  4],
        [-2, 17,  9, 10]]),
 array([[10, 21,  7, 16],
        [10, 19,  6,  8]]))

In [31]:
#reorganizing
c.size
c.reshape((2,6,2))

array([[[ 2,  8],
        [ 6,  8],
        [ 5,  9],
        [ 3,  2],
        [ 9,  5],
        [-5,  0]],

       [[ 6,  1],
        [ 0,  4],
        [-1,  8],
        [ 6,  8],
        [-1,  9],
        [ 3,  2]]])

In [32]:
#vertical stacking
x = stats.reshape((8,2))
y = b.reshape((3,2))
x.shape, y.shape

((8, 2), (3, 2))

In [33]:
x,y

(array([[2, 8],
        [6, 8],
        [5, 9],
        [3, 2],
        [9, 5],
        [7, 0],
        [6, 1],
        [0, 4]]),
 array([[6, 6],
        [6, 6],
        [6, 6]]))

In [34]:
np.vstack((x,y))

array([[2, 8],
       [6, 8],
       [5, 9],
       [3, 2],
       [9, 5],
       [7, 0],
       [6, 1],
       [0, 4],
       [6, 6],
       [6, 6],
       [6, 6]])

In [35]:
h = x.reshape((2,8))
g = y.reshape((2,3))
np.hstack((h,g))

array([[2, 8, 6, 8, 5, 9, 3, 2, 6, 6, 6],
       [9, 5, 7, 0, 6, 1, 0, 4, 6, 6, 6]])

In [36]:
#getting datafrom txt file
#data = np.genfromtxt('data.txt', delimiter=',')

# boolean masking

In [37]:
print(c > 4)
stats[stats > 5]


[[[False  True  True  True]
  [ True  True False False]]

 [[ True  True False False]
  [ True False False False]]

 [[False  True  True  True]
  [False  True False False]]]


array([8, 6, 8, 9, 9, 7, 6])

In [38]:
f = c[c > 4]
f

array([8, 6, 8, 5, 9, 9, 5, 6, 8, 6, 8, 9])

In [39]:
f[[1, 5, 8]] #indexing

array([6, 9, 8])

In [40]:
ex = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
ex

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [41]:
t = (ex>1) & (ex<21) & (ex%2==0) & (ex%3!=0)
t

array([[False,  True, False,  True, False],
       [False, False,  True, False,  True],
       [False, False, False,  True, False],
       [ True, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [42]:
ex[t], ex[[0,1,2,3], [1,2,3,4]]

(array([ 2,  4,  8, 10, 14, 16, 20]), array([ 2,  8, 14, 20]))

In [43]:
ex[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

# machine learning model: 
## decision tree

In [44]:
import sklearn as sk